# Generated by Django 2.2.4 on 2019-09-27 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='DEFAULT NAME', max_length=50)),
                ('tag', models.CharField(default='DEFAULT STRING', max_length=50)),
                ('type', models.CharField(default='rectangle', max_length=50)),
                ('color', models.CharField(default='white', max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('firstTime', models.CharField(default='0:00', max_length=8)),
                ('secondTime', models.CharField(default='0:00', max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('videoFile', models.FileField(null=True, upload_to='uploads/')),
                ('videoFile1', models.FileField(null=True, upload_to='uploads/')),
                ('isGlobal', models.BooleanField(default=True)),
                ('userUploader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(default='#', max_length=50)),
                ('text', models.CharField(default='NEW_ITEM', max_length=50)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileManager.Video')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalAnnotationVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='DEFAULT STRING', max_length=50)),
                ('firstTime', models.CharField(default='0:00', max_length=8)),
                ('secondTime', models.CharField(default='0:00', max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileManager.Video')),
            ],
        ),
        migrations.CreateModel(
            name='FrameLevelAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstPointX', models.FloatField(default=0)),
                ('firstPointY', models.FloatField(default=0)),
                ('deltaX', models.FloatField(default=0)),
                ('deltaY', models.FloatField(default=0)),
                ('reminderX', models.FloatField(default=0)),
                ('reminderY', models.FloatField(default=0)),
                ('frame', models.IntegerField(default=0)),
                ('annotationVideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileManager.AnnotationVideo')),
            ],
        ),
        migrations.AddField(
            model_name='annotationvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileManager.Video'),
        ),
    ]
